== Digital Value Delivery

Hello and welcome! You have stumbled upon an evolving, "open book"; a free and open-source book with https://www.ourchitecture.io/chomping-at-the-bit/license/[a permissive ((license))].

Our goal is to drastically improve ((digital transformation)) efforts by establishing a standardized language for digital value delivery along with a collection of patterns that you can customize and apply in your own organizations.

Of course, these resources require time and effort. https://www.patreon.com/ourchitecture[Please support us.]

=== The Bit

Imagining the flow of bits and bytes in a computer system might invoke images from a movie like "The Matrix".

The bit is the most basic unit of information in computing and digital communications. The name is a portmanteau of binary digit. The bit represents a logical state with one of two possible values. These values are most commonly represented as either `"1"` or `"0"`, but other representations such as `true/false`, `yes/no`, `+/−`, or `on/off` are commonly used.

The inherent complexity and challenges of digital experiences and capabilities can be daunting. Beyond the "bit", unlocking the value of technology rarely presents itself as a binary decision or solution, but as a vast collection of concerns and dependencies.

It is interesting that the "bit" in the equestrian world, is a tool that helps connect a rider and a horse, aiding in communication and directing the horse's path. For horses, "bit chomping" or "bit champing" may indicate an issue with size, shape and fit, but often indicates that the horse is nervous, anxious, or impatient about something.

[quote]
If a person is "chomping / champing at the bit", they are very impatient to do something, but they are prevented from doing it, usually by circumstances that they have no control over.

Like a Pacman character devouring dots, digital value delivery affords us the "chomping at the bit" experience of literally chomping at the bit every day; wanting to offer better digital experiences and new and improved business capabilities! Business and technology experts alike have incredible ideas about the value they would like to deliver to customers, but run into roadblocks and obstacles along the way; developers experience this constantly while iterating in short cycles with small coding experiments that grow into full-fledged features and capabilities.

Technology can be exciting and offer great potential. In this project, we will establish a basic, working language to understand the complexity and challenges of digital value delivery and define some patterns for constant improvement.

* The Four Resources
* The Four Structures
* The Four Lifecycle Stages
* The Three Concerns
