== Resources

(((Excellence, People)))
(((Excellence, Process)))
(((Excellence, Technology)))
(((just cause)))
The traditional Information Technology triangle of considering "People", "Process", and "Technology" has proved incredibly useful over the years, but has always missed a critical alignment segment: "((Value))" or even more fundamentally "((Why))?". Why would we bring these three together and for what purpose? What is their mission or https://simonsinek.com/discover/great-leaders-organizations-advance-a-just-cause/["just cause"] as ((Simon Sinek)) might put it?

.Value delivery resources
image::./assets/graphics/diagrams/value-delivery-resources.svg[]

=== Value

Everything an organization does can be tied back to a value proposition or ((hypothesis)). Like any ((experiment)), the result may be failure. Even wasteful activities that started with a specific context of intentions, assumptions and expectations may have been wrong to begin with, wrong in hindsight or retrospect, or the context has changed and partially or completely no longer applies. The goal, of course, is to maximize value delivery and minimize waste. Customer value is often assumed, but it could be wrong to jump to the conclusion that priority is always given to a customer's value, because there are often many important stakeholders concerned with their own definitions of "value" as well as unique value delivery concerns. Operating an organization means prioritizing, balancing and maximizing value delivery across all concerned stakeholders.

=== People

Most every organization has people ((leadership)) for strategy and ((management)) for execution. Looking for opportunities through the lens of "People" can offer unique insights into ((team structures)), ((telecommuting)) or "((work from home))" (((WFH))), ((diversity and inclusion)), ((talent management)) including ((recruiting)), ((upskilling)) and ((reskilling)), ((internships)) and https://www.themuse.com/advice/what-is-a-returnship-hint-something-you-probably-want-to-check-out-if-youre-returning-to-the-workforce[((returnships))] and more.

Creating organizational structures around people, uninformed explicitly by the (((technology roadmap, roadmap))) can result in "((Conway's Law))".

[quote, Melvin E. Conway]
Any organization that designs a system (defined broadly) will produce a design whose structure is a copy of the organization's communication structure.

Organizations, especially large enterprises, often struggle with the reality of Conway's Law and the negative friction it can introduce to digital value delivery. Organizations may apply https://blog.octo.com/how-to-deal-with-an-inverse-conway-maneuver-a-talk-by-romain-vailleux-at-duck-conf-2021/[the "((Inverse Conway Maneuver))"] by working closely with their systems designers / architects and technology leaders as well as using tools like https://teamtopologies.com/[((Team Topologies))]. ((Stephen Covey)) stated this simply in https://www.franklincovey.com/habit-2/[Habit 2] of "((The 7 Habits of Highly Effective People))" as "begin with the end in mind."

(((Excellence, People)))
[TIP]
.People excellence
====
People ((leadership)) has evolved out of traditional top-down management and is well-established through the practice of organizational management and leadership. Because people are uniquely complex, especially when scaling from an individual to an enterprise, and they exist in an evolving world of generations, each leadership context offers its own distinct insights with many paths leading toward varying degrees of success. Generally, people want to be valued, to be personally connected to the value they are generating for an organization, and to be recognized for their contributions.
====

=== Process

((Waterfall Model))
Approaches toward optimizing value delivery processes have continued to evolve out of the traditional https://en.wikipedia.org/wiki/Waterfall_model["Waterfall Model"] with involved process improvement practices like ((Six Sigma)) and into variations of ((Agile)), ((Scrum)), ((Lean)), ((Kanban)) and others including adapting improvement frameworks like ((Lean Six Sigma)). Establishing https://agilemanifesto.org/[the ((Agile Manifesto))] brought a sense of unity to process discussions and possibly improved the probability of organizations being willing to change and try something new. Improving value delivery with tools like https://en.wikipedia.org/wiki/Value-stream_mapping[((Value-Stream mapping))] with prioritized focus and iterative improvements can pay great dividends.

(((Excellence, Process)))
[TIP]
.Process excellence
====
Process leadership has generally focused on tighter and leaner value delivery models that offer earlier feedback for what is working and what is not. The technology "((DevOps))" movement refers to this earlier feedback cycle as "shift left", where the spectrum of value delivery is designed and developed on the left-hand side of the scale and and is realized on the right; where possible, important feedback to inform decision making is gathered earlier toward value design and development.
====

=== Technology

Technology is a vital asset to most businesses today, giving rise to the "((digital enterprise))" and "((digital transformation))" efforts. Technology is most useful when end-users and stakeholders alike agree that it provides value for them now. Past value quickly results in a liability for organizations while future value predictions are experiments, behaving like a stock option that may or may not yield a return on investment. Experimenting with value delivery improvements and value propositions to end users can be an asset that informs investments, but non-production value, i.e. value that is not yet available to end users, is a liability to the organization until it is delivered.

(((Excellence, Technology)))
[TIP]
.Technology excellence
====
There are many forms of technology leadership in an organization. Utilized effectively in an enterprise, the diversity of expertise can breed tremendous innovation. In practice, the boundaries for decision making get blurred across roles from developers and engineers to designers and architects to management and leadership as well as other technology consultants and experts. Some of the best tools for managing technology leadership concerns may come from the practice of architecture including the roles of ((Enterprise Architecture)), ((Business Architecture)), ((Solutions Architecture)), ((Experience Architecture)), ((Software Architecture)) and ((Application Architecture)), ((Data Architecture)) and ((Information Architecture)), and ((Infrastructure Architecture)). The designers of an organization's technology are many and often do not hold the title "designer" or "architect". The consequences of decision making may result in unanticipated opportunities as well as challenges for the future.
====

=== Conclusions

Great solutions need to account for and balance opportunities and risks across all of these four resources; improving value delivery by investing in people through iterative process with the right technology. The four structures begin to inform our organizational strategy and structure.
